<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <RootNamespace>DfE.EducationProviderRegistry.Core.Query.IntegrationTests</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings*.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MartinCostello.Logging.XUnit.v3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Xunit.DependencyInjection" />
    <PackageReference Include="Xunit.DependencyInjection.Logging" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DfE.EducationProviderRegistry.Core.Query\DfE.EducationProviderRegistry.Core.Query.csproj" />
    <ProjectReference Include="..\IntegrationTests.Abstractions\IntegrationTests.Abstractions.csproj" />
    <ProjectReference Include="..\IntegrationTests.Database.Server.Abstractions\IntegrationTests.Database.Server.Abstractions.csproj" />
    <ProjectReference Include="..\IntegrationTests.Database.Server.Postgres\IntegrationTests.Database.Server.Postgres.csproj" />
  </ItemGroup>

</Project>
